######################################################################
# Automatically generated by qmake (3.0) Thu Sep 15 14:28:53 2016
######################################################################

TEMPLATE = app
TARGET = qt_testing
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
